<<<<<<< HEAD
mode: train
  # mode: test

  # arch: CustomNetwork
  # arch: RelationNetwork
arch: MatchingNetwork
=======
train: True
test: False

arch: CustomNetwork
# arch: RelationNetwork
# arch: MatchingNetwork
>>>>>>> fe30df3164aee34c679770f46be3d2a8d10170df

name: 20-way-1-shot

dataset: Omniglot
  # dataset: miniImageNet

loss_fn: MSE
  # loss_fn: NLL
  # loss_fn: CrossEntropy

k: 20 # Number of classes
n: 1 # Number of examples per support class
m: 19 # Number of examples per query class

epochs: 250
learning_rate: 0.001
schedule:
  - 40
  - 250
  - 1000
