train: True
test: False

# arch: CustomNetwork
arch: RelationNetwork
# arch: MatchingNetwork

name: 20-way-5-shot

dataset: Omniglot
# dataset: miniImageNet

loss_fn: MSE
# loss_fn: NLL
# loss_fn: CrossEntropy

k: 20 # Number of classes
n: 5 # Number of examples per support class
m: 15 # Number of examples per query class

epochs: 500
learning_rate: 0.001
schedule:
  - 40
  - 250
  - 1000
