graph_dir_path: ./analysis/graphs/20way-1shot
logdatas:
  - relnet:
    label: "RelNet, 20 way, 1-shot"
    path: ./saves/RelationNetwork/20-way-1-shot/log
  - matchnet:
    label: "MatchNet, 20 way, 1-shot"
    path: ./saves/MatchingNetwork/20-way-1-shot/log
  - customnet:
    label: "CustomNet, 20 way, 1-shot"
    path: ./saves/CustomNetwork/20-way-1-shot/log
