graph_dir_path: ./analysis/graphs/custom-5way
logdatas:
  - relnet5_5:
    label: "CustomNet, 5 way, 5-shot"
    path: ./saves/CustomNetwork/5-way-5-shot/log
  - relnet5_1:
    label: "CustomNet, 5 way, 1-shot"
    path: ./saves/CustomNetwork/5-way-1-shot/log
